In [1]:
!git clone https://github.com/Shubham-joshi20/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning.git

Cloning into 'Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning'...
remote: Enumerating objects: 75, done.
remote: Counting objects: 100% (75/75), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 75 (delta 31), reused 62 (delta 23), pack-reused 0 (from 0)
Receiving objects: 100% (75/75), 32.88 KiB | 5.48 MiB/s, done.
Resolving deltas: 100% (31/31), done.

In [2]:
%cd /kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning

/kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning

In [3]:
!git pull origin main

From https://github.com/Shubham-joshi20/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning
 * branch            main       -> FETCH_HEAD
Already up to date.

In [4]:
pip install -q -r requirements.txt

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 948.2/948.2 kB 13.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 64.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.

In [5]:
from pathlib import Path

for path in Path("/kaggle/input").rglob("*"):
    if path.is_file():
        print(path)

/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv
/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv

In [6]:
!python scripts/prepare_nq.py \
  --input /kaggle/input/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv//kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv \
  --output data/processed/train.jsonl \
  --split train \
  --limit 5000

Traceback (most recent call last):
  File "/kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning/scripts/prepare_nq.py", line 32, in <module>
    main()
    ~~~~^^
  File "/kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning/scripts/prepare_nq.py", line 27, in main
    summary = prepare_subset(args.input, args.output, args.split, args.limit, args.seed)
  File "/kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning/src/search_rl/data.py", line 127, in prepare_subset
    records = read_records(input_path)
  File "/kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning/src/search_rl/data.py", line 109, in read_records
    with path.open(newline="", encoding="utf-8-sig") as handle:
         ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/pathlib/_local.py", line 537, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv'

In [7]:
!git clone https://github.com/Shubham-joshi20/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning.git

Cloning into 'Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning'...
remote: Enumerating objects: 75, done.
remote: Counting objects: 100% (75/75), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 75 (delta 31), reused 62 (delta 23), pack-reused 0 (from 0)
Receiving objects: 100% (75/75), 32.88 KiB | 10.96 MiB/s, done.
Resolving deltas: 100% (31/31), done.

In [8]:
cd Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning

/kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning

In [9]:
!python scripts/prepare_nq.py

usage: prepare_nq.py [-h] --input INPUT --output OUTPUT [--split SPLIT]
                     [--limit LIMIT] [--seed SEED]
prepare_nq.py: error: the following arguments are required: --input, --output

In [10]:
!git pull origin main

From https://github.com/Shubham-joshi20/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning
 * branch            main       -> FETCH_HEAD
Already up to date.

In [11]:
from pathlib import Path

for path in Path("/kaggle/input/datasets/frankossai/natural-questions-dataset").rglob("*"):
    if path.is_file():
        print(path)

/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv
/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv

In [12]:
import pandas as pd

base_path = "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv"
filtered_path = "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv"

for path in [base_path, filtered_path]:
    df = pd.read_csv(path)
    print("\nFILE:", path)
    print("Shape:", df.shape)
    print("Columns:", list(df.columns))
    display(df.head(2))

FILE: /kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv
Shape: (307373, 3)
Columns: ['question', 'long_answers', 'short_answers']

,question,long_answers,short_answers
0,which is the most common use of opt-in e-mail ...,<P> A common example of permission marketing i...,a newsletter sent to an advertising firm 's cu...
1,how i.met your mother who is the mother,"<P> Tracy McConnell , better known as `` The M...",Tracy McConnell

FILE: /kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv
Shape: (86212, 3)
Columns: ['question', 'long_answers', 'short_answers']

,question,long_answers,short_answers
0,which is the most common use of opt-in e-mail ...,A common example of permission marketing is a ...,A newsletter sent to an advertising firm's cus...
1,how i.met your mother who is the mother,"Tracy McConnell, better known as `` The Mother...",Tracy McConnell

In [13]:
%run scripts/prepare_nq.py --input "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv" --output "/kaggle/working/data/processed/train.jsonl" --split train --limit 5000 --seed 42

{
  "input_records": 86212,
  "usable_records": 86212,
  "written_records": 5000
}

In [14]:
!pip install -q -r requirements.txt

In [15]:
import pandas as pd

path = "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv"

df = pd.read_csv(path)
print(df.columns.tolist())
display(df.head(2))

['question', 'long_answers', 'short_answers']

,question,long_answers,short_answers
0,which is the most common use of opt-in e-mail ...,A common example of permission marketing is a ...,A newsletter sent to an advertising firm's cus...
1,how i.met your mother who is the mother,"Tracy McConnell, better known as `` The Mother...",Tracy McConnell

In [16]:
%run scripts/prepare_passages.py --input "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv" --output "/kaggle/working/data/processed/passages.jsonl" --max-records 5000

Wrote 6453 passages to /kaggle/working/data/processed/passages.jsonl

In [17]:
import pandas as pd

base_path = "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv"
filtered_path = "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv"

for path in [filtered_path, base_path]:
    df = pd.read_csv(path)
    print("\nFILE:", path)
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())
    display(df.head(1).T)

FILE: /kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv
Shape: (86212, 3)
Columns: ['question', 'long_answers', 'short_answers']

                                                               0
question       which is the most common use of opt-in e-mail ...
long_answers   A common example of permission marketing is a ...
short_answers  A newsletter sent to an advertising firm's cus...

FILE: /kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv
Shape: (307373, 3)
Columns: ['question', 'long_answers', 'short_answers']

                                                               0
question       which is the most common use of opt-in e-mail ...
long_answers   <P> A common example of permission marketing i...
short_answers  a newsletter sent to an advertising firm 's cu...

In [18]:
df = pd.read_csv(base_path)

possible_columns = [
    "document_text",
    "context",
    "passage",
    "long_answer",
    "document",
    "text"
]

for column in possible_columns:
    if column in df.columns:
        print(column, "non-empty values:", df[column].notna().sum())
        print(df[column].dropna().iloc[0][:500])

In [19]:
!git pull origin main

From https://github.com/Shubham-joshi20/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning
 * branch            main       -> FETCH_HEAD
Already up to date.

In [20]:
%run scripts/prepare_passages.py \
  --input "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv" \
  --output "/kaggle/working/data/processed/passages.jsonl" \
  --max-records 5000 \
  --words-per-passage 120

Wrote 6453 passages to /kaggle/working/data/processed/passages.jsonl

In [21]:
from pathlib import Path

path = Path("/kaggle/working/data/processed/passages.jsonl")

print("Passage file exists:", path.exists())
print("Number of passages:", len(path.read_text(encoding="utf-8").splitlines()))
print(path.read_text(encoding="utf-8").splitlines()[:2])

Passage file exists: True
Number of passages: 6453
['{"id": "nq-0-0", "text": "A common example of permission marketing is a newsletter sent to an advertising firm\'s customers. Such newsletters inform customers of upcoming events or promotions, or new products. In this type of advertising, a company that wants to send a newsletter to their customers may ask them at the point of purchase if they would like to receive the newsletter."}', '{"id": "nq-1-0", "text": "Tracy McConnell, better known as `` The Mother \'\', is the title character from the CBS television sitcom How I Met Your Mother. The show, narrated by Future Ted, tells the story of how Ted Cosby met The Mother. Tracy McConnell appears in episodes from `` Lucky Penny \'\' to `` The Time Travelers \'\' as an unseen character ; she was first seen fully in `` Something New \'\' and was promoted to a main character in season. The Mother is played by Cristina Militia."}']

In [22]:
%run scripts/run_rollout_smoke.py \
  --passages "/kaggle/working/data/processed/passages.jsonl"

{
  "question": "Who wrote Hamlet?",
  "text": "<think>I need evidence.</think><search>author of Hamlet</search><think>The evidence identifies the author.</think><answer>William Shakespeare</answer>",
  "answer": "William Shakespeare",
  "searches": [
    {
      "query": "author of Hamlet",
      "passages": [
        {
          "id": "nq-553-0",
          "text": "Hamlet jokes with Claudius about where he has hidden Polonius's body, and the king, fearing for his life, sends Rosencrantz and Guildenstern to accompany Hamlet to England with a sealed letter to the English king requesting that Hamlet be executed immediately.",
          "score": 13.531606
        },
        {
          "id": "nq-4811-120",
          "text": "Batman (Affleck) into a preemptive battle with Superman (Cavils) , who Author is obsessed with defeating.",
          "score": 7.539236
        },
        {
          "id": "nq-3185-0",
          "text": "Charlie and the Chocolate Factory is a 1964 children's novel by British author Roald Dahl. The story features the adventures of young Charlie Bucket inside the chocolate factory of eccentric chocolate Willy Wonka.",
          "score": 6.83741
        }
      ]
    }
  ],
  "termination": "answer",
  "latency_seconds": 0.05592397200001642
}

In [23]:
%run scripts/prepare_nq.py \
  --input "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv" \
  --output "/kaggle/working/data/processed/validation.jsonl" \
  --split validation \
  --limit 500 \
  --seed 123

{
  "input_records": 86212,
  "usable_records": 86212,
  "written_records": 500
}

In [24]:
!python scripts/run_qwen_baseline.py \
  --questions "/kaggle/working/data/processed/validation.jsonl" \
  --passages "/kaggle/working/data/processed/passages.jsonl" \
  --output "/kaggle/working/artifacts/qwen05b_rollouts.jsonl" \
  --limit 100

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
config.json: 100%|█████████████████████████████| 659/659 [00:00<00:00, 1.55MB/s]
tokenizer_config.json: 100%|███████████████| 7.30k/7.30k [00:00<00:00, 21.2MB/s]
vocab.json: 100%|██████████████████████████| 2.78M/2.78M [00:00<00:00, 49.4MB/s]
merges.txt: 100%|███████████████████████████| 1.67M/1.67M [00:00<00:00, 108MB/s]
tokenizer.json: 100%|███████████████████████| 7.03M/7.03M [00:00<00:00, 137MB/s]
Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so
Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so

model.safetensors: downloading bytes:                       | 2.80MB
model.safetensors: downloading bytes: ████▎                 |  192MB, 15.0MB/s
model.safetensors: downloading bytes: ██████▎               |  282MB, 22.4MB/s
model.safetensors: downloading bytes: █████████▏            |  410MB, 33.8MB/s
model.safetensors: downloading bytes: ███████████▍          |  514MB, 42.9MB/s
model.safetensors: downloading bytes: ██████████████▉       |  669MB, 56.4MB/s
model.safetensors: downloading bytes: █████████████████▏    |  774MB, 64.9MB/s
model.safetensors: reconstructing file:  68%|████  |  671MB /  988MB, 55.1MB/s
model.safetensors: downloading bytes: ██████████████████▋   |  840MB, 72.9MB/s
model.safetensors: downloading bytes: ██████████████████████|  854MB, 74.9MB/s
model.safetensors: reconstructing file: 100%|██████|  988MB /  988MB, 88.2MB/s
Loading weights: 100%|███████████████████████| 290/290 [00:00<00:00, 860.40it/s]
generation_config.json: 100%|███████████████████| 242/242 [00:00<00:00, 811kB/s]
1: EM=0 F1=0.000
2: EM=0 F1=0.000
3: EM=0 F1=0.000
4: EM=0 F1=0.167
5: EM=0 F1=0.000
6: EM=0 F1=0.000
7: EM=0 F1=0.308
8: EM=0 F1=0.000
9: EM=0 F1=0.000
10: EM=0 F1=0.000
11: EM=0 F1=0.057
12: EM=0 F1=0.300
13: EM=0 F1=0.000
14: EM=0 F1=0.000
15: EM=0 F1=0.100
16: EM=0 F1=0.000
17: EM=0 F1=0.000
18: EM=0 F1=0.000
19: EM=0 F1=0.010
20: EM=0 F1=0.000
21: EM=0 F1=0.000
22: EM=0 F1=0.000
23: EM=0 F1=0.057
24: EM=0 F1=0.108
25: EM=0 F1=0.000
26: EM=0 F1=0.800
27: EM=0 F1=0.000
28: EM=0 F1=0.000
29: EM=0 F1=0.000
30: EM=0 F1=0.006
31: EM=0 F1=0.105
32: EM=0 F1=0.000
33: EM=0 F1=0.000
34: EM=0 F1=0.000
35: EM=0 F1=0.000
36: EM=0 F1=0.400
37: EM=0 F1=0.000
38: EM=0 F1=0.000
39: EM=0 F1=0.000
40: EM=0 F1=0.250
41: EM=0 F1=0.000
42: EM=0 F1=0.000
43: EM=0 F1=0.000
44: EM=0 F1=0.000
45: EM=0 F1=0.000
46: EM=0 F1=0.000
47: EM=0 F1=0.000
48: EM=0 F1=0.000
49: EM=0 F1=0.286
50: EM=0 F1=0.000
51: EM=0 F1=0.000
52: EM=0 F1=0.000
53: EM=0 F1=0.034
54: EM=0 F1=0.000
55: EM=0 F1=0.190
56: EM=0 F1=0.000
57: EM=0 F1=0.000
58: EM=0 F1=0.118
59: EM=0 F1=0.100
60: EM=0 F1=0.000
61: EM=0 F1=0.091
62: EM=0 F1=0.000
63: EM=0 F1=0.000
64: EM=0 F1=0.000
65: EM=0 F1=0.000
66: EM=0 F1=0.000
67: EM=0 F1=0.000
68: EM=0 F1=0.000
69: EM=1 F1=1.000
70: EM=0 F1=0.012
71: EM=0 F1=0.267
72: EM=0 F1=0.000
73: EM=0 F1=0.000
74: EM=0 F1=0.500
75: EM=0 F1=0.000
76: EM=0 F1=0.078
77: EM=0 F1=0.000
78: EM=0 F1=0.000
79: EM=0 F1=0.258
80: EM=0 F1=0.105
81: EM=0 F1=0.000
82: EM=0 F1=0.067
83: EM=0 F1=0.000
84: EM=0 F1=0.125
85: EM=0 F1=0.000
86: EM=0 F1=0.000
87: EM=0 F1=0.000
88: EM=0 F1=0.000
89: EM=0 F1=0.129
90: EM=0 F1=0.000
91: EM=0 F1=0.000
92: EM=0 F1=0.000
93: EM=0 F1=0.200
94: EM=0 F1=0.167
95: EM=0 F1=0.000
96: EM=0 F1=0.000
97: EM=0 F1=0.000
98: EM=0 F1=0.333
99: EM=0 F1=0.061
100: EM=0 F1=0.074

In [25]:
!git pull origin main

From https://github.com/Shubham-joshi20/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning
 * branch            main       -> FETCH_HEAD
Already up to date.

In [26]:
!python scripts/evaluate_rollouts.py \
  --input /kaggle/working/artifacts/qwen05b_rollouts.jsonl \
  --output /kaggle/working/artifacts/baseline_metrics.json

{
  "examples": 100,
  "exact_match": 0.01,
  "token_f1": 0.06861335038342968,
  "reward": 0.033906675191714836,
  "valid_format_rate": 0.95,
  "search_rate": 0.25,
  "average_searches": 0.27
}

In [27]:
!cat /kaggle/working/artifacts/baseline_metrics.json

{
  "examples": 100,
  "exact_match": 0.01,
  "token_f1": 0.06861335038342968,
  "reward": 0.033906675191714836,
  "valid_format_rate": 0.95,
  "search_rate": 0.25,
  "average_searches": 0.27
}

In [28]:
import shutil

shutil.make_archive(
    "/kaggle/working/search_rl_baseline",
    "zip",
    root_dir="/kaggle/working/artifacts"
)

'/kaggle/working/search_rl_baseline.zip'

In [29]:
!git pull origin main

From https://github.com/Shubham-joshi20/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning
 * branch            main       -> FETCH_HEAD
Already up to date.

In [30]:
!pip install -q -r requirements.txt

In [31]:
import torch

print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

CUDA available: True
Tesla T4

In [32]:
import torch

print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

CUDA available: True
Tesla T4

In [33]:
!git clone https://github.com/Shubham-joshi20/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning.git

Cloning into 'Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning'...
remote: Enumerating objects: 75, done.
remote: Counting objects: 100% (75/75), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 75 (delta 31), reused 62 (delta 23), pack-reused 0 (from 0)
Receiving objects: 100% (75/75), 32.88 KiB | 8.22 MiB/s, done.
Resolving deltas: 100% (31/31), done.

In [34]:
%cd /kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning

/kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning

In [35]:
!ls scripts

evaluate_rollouts.py  prepare_passages.py   run_rollout_smoke.py
prepare_nq.py	      run_qwen_baseline.py  train_rl.py

In [36]:
!pip install -q -r requirements.txt

In [37]:
!python -m unittest discover -s tests -v

test_answer_metrics_normalize_articles_and_case (test_core.CoreTests.test_answer_metrics_normalize_articles_and_case) ... ok
test_bm25_returns_relevant_passage_first (test_core.CoreTests.test_bm25_returns_relevant_passage_first) ... ok
test_extract_passages_supports_nq_long_answers (test_core.CoreTests.test_extract_passages_supports_nq_long_answers) ... ok
test_read_records_accepts_directory_with_one_data_file (test_core.CoreTests.test_read_records_accepts_directory_with_one_data_file) ... ok
test_reward_combines_em_f1_and_penalizes_invalid_format (test_core.CoreTests.test_reward_combines_em_f1_and_penalizes_invalid_format) ... ok
test_rollout_inserts_evidence_and_stops_at_answer (test_core.CoreTests.test_rollout_inserts_evidence_and_stops_at_answer) ... ok
test_summary_accepts_older_rollout_metrics_without_gold_answers (test_core.CoreTests.test_summary_accepts_older_rollout_metrics_without_gold_answers) ... ok
test_summary_reports_search_and_reward_statistics (test_core.CoreTests.test_summary_reports_search_and_reward_statistics) ... ok

----------------------------------------------------------------------
Ran 8 tests in 0.004s

OK

In [38]:
from pathlib import Path

for path in Path("/kaggle/input").rglob("*"):
    if path.is_file():
        print(path)

/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv
/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv

In [39]:
!mkdir -p data/raw data/processed artifacts

In [40]:
!python scripts/prepare_nq.py \
  --input "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv" \
  --output "data/processed/train.jsonl" \
  --split train \
  --limit 5000 \
  --seed 42

{
  "input_records": 86212,
  "usable_records": 86212,
  "written_records": 5000
}

In [41]:
!python scripts/prepare_nq.py \
  --input "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv" \
  --output "data/processed/validation.jsonl" \
  --split validation \
  --limit 500 \
  --seed 123

{
  "input_records": 86212,
  "usable_records": 86212,
  "written_records": 500
}

In [42]:
from pathlib import Path

for path in [
    Path("data/processed/train.jsonl"),
    Path("data/processed/validation.jsonl"),
]:
    print(path, path.exists(), len(path.read_text(encoding="utf-8").splitlines()))

data/processed/train.jsonl True 5000
data/processed/validation.jsonl True 500

In [43]:
!python scripts/prepare_passages.py \
  --input "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv" \
  --output "data/processed/passages.jsonl" \
  --max-records 5000 \
  --words-per-passage 120

Wrote 6453 passages to data/processed/passages.jsonl

In [44]:
from pathlib import Path

path = Path("data/processed/passages.jsonl")
print("Exists:", path.exists())
print("Passages:", len(path.read_text(encoding="utf-8").splitlines()))
print(path.read_text(encoding="utf-8").splitlines()[:1])

Exists: True
Passages: 6453
['{"id": "nq-0-0", "text": "A common example of permission marketing is a newsletter sent to an advertising firm\'s customers. Such newsletters inform customers of upcoming events or promotions, or new products. In this type of advertising, a company that wants to send a newsletter to their customers may ask them at the point of purchase if they would like to receive the newsletter."}']

In [45]:
!python scripts/run_rollout_smoke.py \
  --passages data/processed/passages.jsonl

{
  "question": "Who wrote Hamlet?",
  "text": "<think>I need evidence.</think><search>author of Hamlet</search><think>The evidence identifies the author.</think><answer>William Shakespeare</answer>",
  "answer": "William Shakespeare",
  "searches": [
    {
      "query": "author of Hamlet",
      "passages": [
        {
          "id": "nq-553-0",
          "text": "Hamlet jokes with Claudius about where he has hidden Polonius's body, and the king, fearing for his life, sends Rosencrantz and Guildenstern to accompany Hamlet to England with a sealed letter to the English king requesting that Hamlet be executed immediately.",
          "score": 13.531606
        },
        {
          "id": "nq-4811-120",
          "text": "Batman (Affleck) into a preemptive battle with Superman (Cavils) , who Author is obsessed with defeating.",
          "score": 7.539236
        },
        {
          "id": "nq-3185-0",
          "text": "Charlie and the Chocolate Factory is a 1964 children's novel by British author Roald Dahl. The story features the adventures of young Charlie Bucket inside the chocolate factory of eccentric chocolate Willy Wonka.",
          "score": 6.83741
        }
      ]
    }
  ],
  "termination": "answer",
  "latency_seconds": 0.0567040050000287
}

In [46]:
!python scripts/train_rl.py \
  --train-data data/processed/train.jsonl \
  --passages data/processed/passages.jsonl \
  --output /kaggle/working/artifacts/qwen05b-search-rl \
  --limit 100 \
  --max-steps 20

Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so
Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|███████████████████████| 290/290 [00:00<00:00, 568.41it/s]
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None}.
{'loss': '0.02573', 'grad_norm': '1.18', 'learning_rate': '1e-05', 'num_tokens': '1003', 'completions/mean_length': '123.5', 'completions/min_length': '119', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '119', 'completions/min_terminated_length': '119', 'completions/max_terminated_length': '119', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.6405', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '13.1', 'epoch': '0.01'}
{'loss': '0.5944', 'grad_norm': '1.554', 'learning_rate': '9.5e-06', 'num_tokens': '1752', 'completions/mean_length': '69.5', 'completions/min_length': '11', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '11', 'completions/min_terminated_length': '11', 'completions/max_terminated_length': '11', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.7221', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.192', 'epoch': '0.02'}
{'loss': '0.4962', 'grad_norm': 'nan', 'learning_rate': '9e-06', 'num_tokens': '2938', 'completions/mean_length': '37', 'completions/min_length': '11', 'completions/max_length': '63', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '37', 'completions/min_terminated_length': '11', 'completions/max_terminated_length': '63', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.842', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '4.308', 'epoch': '0.03'}
{'loss': '0.09729', 'grad_norm': '1.252', 'learning_rate': '8.5e-06', 'num_tokens': '4191', 'completions/mean_length': '112.5', 'completions/min_length': '97', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '97', 'completions/min_terminated_length': '97', 'completions/max_terminated_length': '97', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.7072', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.41', 'epoch': '0.04'}
{'loss': '0.1554', 'grad_norm': '1.146', 'learning_rate': '8e-06', 'num_tokens': '5559', 'completions/mean_length': '91', 'completions/min_length': '71', 'completions/max_length': '111', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '91', 'completions/min_terminated_length': '71', 'completions/max_terminated_length': '111', 'rewards/reward_function/mean': '0.1652', 'rewards/reward_function/std': '0.3321', 'reward': '0.1652', 'reward_std': '0.3321', 'frac_reward_zero_std': '0', 'entropy': '0.473', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '7.281', 'epoch': '0.05'}
{'loss': '0.01985', 'grad_norm': '1.316', 'learning_rate': '7.5e-06', 'num_tokens': '6712', 'completions/mean_length': '124.5', 'completions/min_length': '121', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '121', 'completions/min_terminated_length': '121', 'completions/max_terminated_length': '121', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.7528', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.358', 'epoch': '0.06'}
{'loss': '0.5405', 'grad_norm': '1.886', 'learning_rate': '7e-06', 'num_tokens': '7645', 'completions/mean_length': '72.5', 'completions/min_length': '17', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '17', 'completions/min_terminated_length': '17', 'completions/max_terminated_length': '17', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.9358', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.391', 'epoch': '0.07'}
{'loss': '0.189', 'grad_norm': '1.349', 'learning_rate': '6.5e-06', 'num_tokens': '8777', 'completions/mean_length': '101', 'completions/min_length': '74', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '74', 'completions/min_terminated_length': '74', 'completions/max_terminated_length': '74', 'rewards/reward_function/mean': '0.4583', 'rewards/reward_function/std': '0.766', 'reward': '0.4583', 'reward_std': '0.766', 'frac_reward_zero_std': '0', 'entropy': '0.9627', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.236', 'epoch': '0.08'}
{'loss': '0', 'grad_norm': '0', 'learning_rate': '6e-06', 'num_tokens': '9816', 'completions/mean_length': '41.5', 'completions/min_length': '26', 'completions/max_length': '57', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '41.5', 'completions/min_terminated_length': '26', 'completions/max_terminated_length': '57', 'rewards/reward_function/mean': '0', 'rewards/reward_function/std': '0', 'reward': '0', 'reward_std': '0', 'frac_reward_zero_std': '1', 'entropy': '0.8674', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '3.942', 'epoch': '0.09'}
{'loss': '0.3564', 'grad_norm': '1.647', 'learning_rate': '5.5e-06', 'num_tokens': '1.033e+04', 'completions/mean_length': '85', 'completions/min_length': '42', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '42', 'completions/min_terminated_length': '42', 'completions/max_terminated_length': '42', 'rewards/reward_function/mean': '-0.08077', 'rewards/reward_function/std': '0.0272', 'reward': '-0.08077', 'reward_std': '0.0272', 'frac_reward_zero_std': '0', 'entropy': '0.6174', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.331', 'epoch': '0.1'}
{'loss': '0', 'grad_norm': '0.7697', 'learning_rate': '5e-06', 'num_tokens': '1.143e+04', 'completions/mean_length': '128', 'completions/min_length': '128', 'completions/max_length': '128', 'completions/clipped_ratio': '1', 'completions/mean_terminated_length': '0', 'completions/min_terminated_length': '0', 'completions/max_terminated_length': '0', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.4124', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.415', 'epoch': '0.11'}
{'loss': '-0.2962', 'grad_norm': '3.341', 'learning_rate': '4.5e-06', 'num_tokens': '1.23e+04', 'completions/mean_length': '65.5', 'completions/min_length': '38', 'completions/max_length': '93', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '65.5', 'completions/min_terminated_length': '38', 'completions/max_terminated_length': '93', 'rewards/reward_function/mean': '0.03125', 'rewards/reward_function/std': '0.04419', 'reward': '0.03125', 'reward_std': '0.04419', 'frac_reward_zero_std': '0', 'entropy': '0.5571', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '6.169', 'epoch': '0.12'}
{'loss': '0', 'grad_norm': '1.191', 'learning_rate': '4e-06', 'num_tokens': '1.376e+04', 'completions/mean_length': '128', 'completions/min_length': '128', 'completions/max_length': '128', 'completions/clipped_ratio': '1', 'completions/mean_terminated_length': '0', 'completions/min_terminated_length': '0', 'completions/max_terminated_length': '0', 'rewards/reward_function/mean': '-0.08795', 'rewards/reward_function/std': '0.01704', 'reward': '-0.08795', 'reward_std': '0.01704', 'frac_reward_zero_std': '0', 'entropy': '1.263', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.607', 'epoch': '0.13'}
{'loss': '0.2453', 'grad_norm': '1.206', 'learning_rate': '3.5e-06', 'num_tokens': '1.475e+04', 'completions/mean_length': '95', 'completions/min_length': '62', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '62', 'completions/min_terminated_length': '62', 'completions/max_terminated_length': '62', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.5996', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.338', 'epoch': '0.14'}
{'loss': '0', 'grad_norm': '0', 'learning_rate': '3e-06', 'num_tokens': '1.55e+04', 'completions/mean_length': '21.5', 'completions/min_length': '12', 'completions/max_length': '31', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '21.5', 'completions/min_terminated_length': '12', 'completions/max_terminated_length': '31', 'rewards/reward_function/mean': '0', 'rewards/reward_function/std': '0', 'reward': '0', 'reward_std': '0', 'frac_reward_zero_std': '1', 'entropy': '0.3114', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '2.258', 'epoch': '0.15'}
{'loss': '-0.2137', 'grad_norm': '2.077', 'learning_rate': '2.5e-06', 'num_tokens': '1.641e+04', 'completions/mean_length': '98', 'completions/min_length': '68', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '68', 'completions/min_terminated_length': '68', 'completions/max_terminated_length': '68', 'rewards/reward_function/mean': '-0.07557', 'rewards/reward_function/std': '0.007872', 'reward': '-0.07557', 'reward_std': '0.007872', 'frac_reward_zero_std': '0', 'entropy': '1.131', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.29', 'epoch': '0.16'}
{'loss': '0', 'grad_norm': '0', 'learning_rate': '2e-06', 'num_tokens': '1.742e+04', 'completions/mean_length': '87', 'completions/min_length': '62', 'completions/max_length': '112', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '87', 'completions/min_terminated_length': '62', 'completions/max_terminated_length': '112', 'rewards/reward_function/mean': '0', 'rewards/reward_function/std': '0', 'reward': '0', 'reward_std': '0', 'frac_reward_zero_std': '1', 'entropy': '0.4731', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '7.362', 'epoch': '0.17'}
{'loss': '0', 'grad_norm': '0', 'learning_rate': '1.5e-06', 'num_tokens': '1.846e+04', 'completions/mean_length': '48', 'completions/min_length': '11', 'completions/max_length': '85', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '48', 'completions/min_terminated_length': '11', 'completions/max_terminated_length': '85', 'rewards/reward_function/mean': '0', 'rewards/reward_function/std': '0', 'reward': '0', 'reward_std': '0', 'frac_reward_zero_std': '1', 'entropy': '0.6281', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '5.574', 'epoch': '0.18'}
{'loss': '2.384e-07', 'grad_norm': '0.8601', 'learning_rate': '1e-06', 'num_tokens': '1.974e+04', 'completions/mean_length': '128', 'completions/min_length': '128', 'completions/max_length': '128', 'completions/clipped_ratio': '1', 'completions/mean_terminated_length': '0', 'completions/min_terminated_length': '0', 'completions/max_terminated_length': '0', 'rewards/reward_function/mean': '-0.08936', 'rewards/reward_function/std': '0.01504', 'reward': '-0.08936', 'reward_std': '0.01504', 'frac_reward_zero_std': '0', 'entropy': '0.5267', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.494', 'epoch': '0.19'}
{'loss': '0.1269', 'grad_norm': '1.66', 'learning_rate': '5e-07', 'num_tokens': '2.054e+04', 'completions/mean_length': '108.5', 'completions/min_length': '89', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '89', 'completions/min_terminated_length': '89', 'completions/max_terminated_length': '89', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.8885', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.28', 'epoch': '0.2'}
{'train_runtime': '151.4', 'train_samples_per_second': '0.264', 'train_steps_per_second': '0.132', 'train_loss': '0.1168', 'epoch': '0.2'}
100%|███████████████████████████████████████████| 20/20 [02:31<00:00,  7.57s/it]

In [47]:
!git pull origin main

From https://github.com/Shubham-joshi20/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning
 * branch            main       -> FETCH_HEAD
Already up to date.

In [48]:
!pip install -q --upgrade "torchao>=0.16.0"

In [49]:
!rm -rf /kaggle/working/artifacts/qwen05b-search-rl

In [50]:
!rm -rf /kaggle/working/artifacts/qwen05b-search-rl

In [51]:
!CUDA_VISIBLE_DEVICES=0 python scripts/train_rl.py \
  --train-data data/processed/train.jsonl \
  --passages data/processed/passages.jsonl \
  --output /kaggle/working/artifacts/qwen05b-search-rl \
  --limit 100 \
  --max-steps 20

Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so
Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|███████████████████████| 290/290 [00:00<00:00, 606.38it/s]
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None}.
{'loss': '0.02573', 'grad_norm': '1.18', 'learning_rate': '1e-05', 'num_tokens': '1003', 'completions/mean_length': '123.5', 'completions/min_length': '119', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '119', 'completions/min_terminated_length': '119', 'completions/max_terminated_length': '119', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.6405', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '10.4', 'epoch': '0.01'}
{'loss': '0.5944', 'grad_norm': '1.552', 'learning_rate': '9.5e-06', 'num_tokens': '1752', 'completions/mean_length': '69.5', 'completions/min_length': '11', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '11', 'completions/min_terminated_length': '11', 'completions/max_terminated_length': '11', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.7209', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.151', 'epoch': '0.02'}
{'loss': '0.4962', 'grad_norm': 'nan', 'learning_rate': '9e-06', 'num_tokens': '2938', 'completions/mean_length': '37', 'completions/min_length': '11', 'completions/max_length': '63', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '37', 'completions/min_terminated_length': '11', 'completions/max_terminated_length': '63', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.8419', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '4.261', 'epoch': '0.03'}
{'loss': '0.09729', 'grad_norm': '1.251', 'learning_rate': '8.5e-06', 'num_tokens': '4191', 'completions/mean_length': '112.5', 'completions/min_length': '97', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '97', 'completions/min_terminated_length': '97', 'completions/max_terminated_length': '97', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.7069', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.327', 'epoch': '0.04'}
{'loss': '0.1554', 'grad_norm': '1.145', 'learning_rate': '8e-06', 'num_tokens': '5559', 'completions/mean_length': '91', 'completions/min_length': '71', 'completions/max_length': '111', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '91', 'completions/min_terminated_length': '71', 'completions/max_terminated_length': '111', 'rewards/reward_function/mean': '0.1652', 'rewards/reward_function/std': '0.3321', 'reward': '0.1652', 'reward_std': '0.3321', 'frac_reward_zero_std': '0', 'entropy': '0.4733', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '7.293', 'epoch': '0.05'}
{'loss': '0.01985', 'grad_norm': '1.311', 'learning_rate': '7.5e-06', 'num_tokens': '6712', 'completions/mean_length': '124.5', 'completions/min_length': '121', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '121', 'completions/min_terminated_length': '121', 'completions/max_terminated_length': '121', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.7531', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.218', 'epoch': '0.06'}
{'loss': '0.5405', 'grad_norm': '1.901', 'learning_rate': '7e-06', 'num_tokens': '7645', 'completions/mean_length': '72.5', 'completions/min_length': '17', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '17', 'completions/min_terminated_length': '17', 'completions/max_terminated_length': '17', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.9337', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.247', 'epoch': '0.07'}
{'loss': '0.189', 'grad_norm': '1.339', 'learning_rate': '6.5e-06', 'num_tokens': '8777', 'completions/mean_length': '101', 'completions/min_length': '74', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '74', 'completions/min_terminated_length': '74', 'completions/max_terminated_length': '74', 'rewards/reward_function/mean': '0.4583', 'rewards/reward_function/std': '0.766', 'reward': '0.4583', 'reward_std': '0.766', 'frac_reward_zero_std': '0', 'entropy': '0.9629', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.224', 'epoch': '0.08'}
{'loss': '0', 'grad_norm': '0', 'learning_rate': '6e-06', 'num_tokens': '9816', 'completions/mean_length': '41.5', 'completions/min_length': '26', 'completions/max_length': '57', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '41.5', 'completions/min_terminated_length': '26', 'completions/max_terminated_length': '57', 'rewards/reward_function/mean': '0', 'rewards/reward_function/std': '0', 'reward': '0', 'reward_std': '0', 'frac_reward_zero_std': '1', 'entropy': '0.8672', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '3.865', 'epoch': '0.09'}
{'loss': '0.3564', 'grad_norm': '1.641', 'learning_rate': '5.5e-06', 'num_tokens': '1.033e+04', 'completions/mean_length': '85', 'completions/min_length': '42', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '42', 'completions/min_terminated_length': '42', 'completions/max_terminated_length': '42', 'rewards/reward_function/mean': '-0.08077', 'rewards/reward_function/std': '0.0272', 'reward': '-0.08077', 'reward_std': '0.0272', 'frac_reward_zero_std': '0', 'entropy': '0.6175', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.216', 'epoch': '0.1'}
{'loss': '0', 'grad_norm': '0.7668', 'learning_rate': '5e-06', 'num_tokens': '1.143e+04', 'completions/mean_length': '128', 'completions/min_length': '128', 'completions/max_length': '128', 'completions/clipped_ratio': '1', 'completions/mean_terminated_length': '0', 'completions/min_terminated_length': '0', 'completions/max_terminated_length': '0', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.4126', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.39', 'epoch': '0.11'}
{'loss': '-0.2962', 'grad_norm': '3.341', 'learning_rate': '4.5e-06', 'num_tokens': '1.23e+04', 'completions/mean_length': '65.5', 'completions/min_length': '38', 'completions/max_length': '93', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '65.5', 'completions/min_terminated_length': '38', 'completions/max_terminated_length': '93', 'rewards/reward_function/mean': '0.03125', 'rewards/reward_function/std': '0.04419', 'reward': '0.03125', 'reward_std': '0.04419', 'frac_reward_zero_std': '0', 'entropy': '0.5567', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '6.153', 'epoch': '0.12'}
{'loss': '0', 'grad_norm': '1.192', 'learning_rate': '4e-06', 'num_tokens': '1.376e+04', 'completions/mean_length': '128', 'completions/min_length': '128', 'completions/max_length': '128', 'completions/clipped_ratio': '1', 'completions/mean_terminated_length': '0', 'completions/min_terminated_length': '0', 'completions/max_terminated_length': '0', 'rewards/reward_function/mean': '-0.08795', 'rewards/reward_function/std': '0.01704', 'reward': '-0.08795', 'reward_std': '0.01704', 'frac_reward_zero_std': '0', 'entropy': '1.263', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.603', 'epoch': '0.13'}
{'loss': '0.2453', 'grad_norm': '1.429', 'learning_rate': '3.5e-06', 'num_tokens': '1.475e+04', 'completions/mean_length': '95', 'completions/min_length': '62', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '62', 'completions/min_terminated_length': '62', 'completions/max_terminated_length': '62', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.8715', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.186', 'epoch': '0.14'}
{'loss': '0', 'grad_norm': '0', 'learning_rate': '3e-06', 'num_tokens': '1.55e+04', 'completions/mean_length': '25', 'completions/min_length': '12', 'completions/max_length': '38', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '25', 'completions/min_terminated_length': '12', 'completions/max_terminated_length': '38', 'rewards/reward_function/mean': '0', 'rewards/reward_function/std': '0', 'reward': '0', 'reward_std': '0', 'frac_reward_zero_std': '1', 'entropy': '0.6187', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '2.678', 'epoch': '0.15'}
{'loss': '0', 'grad_norm': '0', 'learning_rate': '2.5e-06', 'num_tokens': '1.648e+04', 'completions/mean_length': '128', 'completions/min_length': '128', 'completions/max_length': '128', 'completions/clipped_ratio': '1', 'completions/mean_terminated_length': '0', 'completions/min_terminated_length': '0', 'completions/max_terminated_length': '0', 'rewards/reward_function/mean': '0', 'rewards/reward_function/std': '0', 'reward': '0', 'reward_std': '0', 'frac_reward_zero_std': '1', 'entropy': '0.6733', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.313', 'epoch': '0.16'}
{'loss': '0', 'grad_norm': '0', 'learning_rate': '2e-06', 'num_tokens': '1.752e+04', 'completions/mean_length': '104.5', 'completions/min_length': '81', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '81', 'completions/min_terminated_length': '81', 'completions/max_terminated_length': '81', 'rewards/reward_function/mean': '-0.1', 'rewards/reward_function/std': '0', 'reward': '-0.1', 'reward_std': '0', 'frac_reward_zero_std': '1', 'entropy': '0.9778', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.255', 'epoch': '0.17'}
{'loss': '0.2354', 'grad_norm': '1.669', 'learning_rate': '1.5e-06', 'num_tokens': '1.865e+04', 'completions/mean_length': '96', 'completions/min_length': '64', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '64', 'completions/min_terminated_length': '64', 'completions/max_terminated_length': '64', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.5829', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.224', 'epoch': '0.18'}
{'loss': '-0.424', 'grad_norm': '4.445', 'learning_rate': '1e-06', 'num_tokens': '1.974e+04', 'completions/mean_length': '27.5', 'completions/min_length': '11', 'completions/max_length': '44', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '27.5', 'completions/min_terminated_length': '11', 'completions/max_terminated_length': '44', 'rewards/reward_function/mean': '0.125', 'rewards/reward_function/std': '0.1768', 'reward': '0.125', 'reward_std': '0.1768', 'frac_reward_zero_std': '0', 'entropy': '0.7035', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '3.186', 'epoch': '0.19'}
{'loss': '0.09021', 'grad_norm': '1.315', 'learning_rate': '5e-07', 'num_tokens': '2.055e+04', 'completions/mean_length': '113.5', 'completions/min_length': '99', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '99', 'completions/min_terminated_length': '99', 'completions/max_terminated_length': '99', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.6111', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.256', 'epoch': '0.2'}
{'train_runtime': '146.4', 'train_samples_per_second': '0.273', 'train_steps_per_second': '0.137', 'train_loss': '0.1163', 'epoch': '0.2'}
100%|███████████████████████████████████████████| 20/20 [02:26<00:00,  7.32s/it]

In [52]:
!find /kaggle/working/artifacts/qwen05b-search-rl \
  -maxdepth 2 \
  -type f

/kaggle/working/artifacts/qwen05b-search-rl/chat_template.jinja
/kaggle/working/artifacts/qwen05b-search-rl/adapter_config.json
/kaggle/working/artifacts/qwen05b-search-rl/tokenizer_config.json
/kaggle/working/artifacts/qwen05b-search-rl/training_args.bin
/kaggle/working/artifacts/qwen05b-search-rl/adapter_model.safetensors
/kaggle/working/artifacts/qwen05b-search-rl/tokenizer.json
/kaggle/working/artifacts/qwen05b-search-rl/training_manifest.json
/kaggle/working/artifacts/qwen05b-search-rl/checkpoint-20/chat_template.jinja
/kaggle/working/artifacts/qwen05b-search-rl/checkpoint-20/adapter_config.json
/kaggle/working/artifacts/qwen05b-search-rl/checkpoint-20/trainer_state.json
/kaggle/working/artifacts/qwen05b-search-rl/checkpoint-20/tokenizer_config.json
/kaggle/working/artifacts/qwen05b-search-rl/checkpoint-20/training_args.bin
/kaggle/working/artifacts/qwen05b-search-rl/checkpoint-20/optimizer.pt
/kaggle/working/artifacts/qwen05b-search-rl/checkpoint-20/scaler.pt
/kaggle/working/artifacts/qwen05b-search-rl/checkpoint-20/scheduler.pt
/kaggle/working/artifacts/qwen05b-search-rl/checkpoint-20/adapter_model.safetensors
/kaggle/working/artifacts/qwen05b-search-rl/checkpoint-20/tokenizer.json
/kaggle/working/artifacts/qwen05b-search-rl/checkpoint-20/README.md
/kaggle/working/artifacts/qwen05b-search-rl/checkpoint-20/rng_state.pth
/kaggle/working/artifacts/qwen05b-search-rl/README.md

In [53]:
!git pull origin main

From https://github.com/Shubham-joshi20/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning
 * branch            main       -> FETCH_HEAD
Already up to date.

In [54]:
!CUDA_VISIBLE_DEVICES=0 python scripts/run_qwen_baseline.py \
  --questions data/processed/validation.jsonl \
  --passages data/processed/passages.jsonl \
  --adapter /kaggle/working/artifacts/qwen05b-search-rl \
  --output /kaggle/working/artifacts/rl_rollouts.jsonl \
  --limit 100

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so
Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so
Loading weights: 100%|███████████████████████| 290/290 [00:00<00:00, 938.83it/s]
1: EM=0 F1=0.000
2: EM=0 F1=0.000
3: EM=0 F1=0.000
4: EM=0 F1=0.071
5: EM=0 F1=0.000
6: EM=0 F1=0.000
7: EM=0 F1=0.296
8: EM=0 F1=0.000
9: EM=0 F1=0.000
10: EM=0 F1=0.000
11: EM=0 F1=0.067
12: EM=0 F1=0.300
13: EM=0 F1=0.000
14: EM=0 F1=0.000
15: EM=0 F1=0.100
16: EM=0 F1=0.000
17: EM=0 F1=0.000
18: EM=0 F1=0.000
19: EM=0 F1=0.007
20: EM=0 F1=0.400
21: EM=0 F1=0.000
22: EM=0 F1=0.000
23: EM=0 F1=0.057
24: EM=0 F1=0.033
25: EM=0 F1=0.000
26: EM=0 F1=0.800
27: EM=0 F1=0.000
28: EM=0 F1=0.000
29: EM=0 F1=0.000
30: EM=0 F1=0.011
31: EM=0 F1=0.000
32: EM=0 F1=0.000
33: EM=0 F1=0.143
34: EM=0 F1=0.017
35: EM=0 F1=0.000
36: EM=0 F1=0.400
37: EM=0 F1=0.000
38: EM=0 F1=0.000
39: EM=0 F1=0.000
40: EM=0 F1=0.250
41: EM=0 F1=0.000
42: EM=0 F1=0.000
43: EM=0 F1=0.000
44: EM=0 F1=0.000
45: EM=0 F1=0.000
46: EM=0 F1=0.000
47: EM=0 F1=0.000
48: EM=0 F1=0.000
49: EM=0 F1=0.286
50: EM=0 F1=0.000
51: EM=0 F1=0.000
52: EM=0 F1=0.000
53: EM=0 F1=0.036
54: EM=0 F1=0.000
55: EM=0 F1=0.214
56: EM=0 F1=0.000
57: EM=0 F1=0.000
58: EM=0 F1=0.211
59: EM=0 F1=0.000
60: EM=0 F1=0.000
61: EM=0 F1=0.091
62: EM=0 F1=0.000
63: EM=0 F1=0.000
64: EM=0 F1=0.000
65: EM=0 F1=0.000
66: EM=0 F1=0.000
67: EM=0 F1=0.000
68: EM=0 F1=0.000
69: EM=1 F1=1.000
70: EM=0 F1=0.011
71: EM=0 F1=0.154
72: EM=0 F1=0.000
73: EM=0 F1=0.000
74: EM=0 F1=0.500
75: EM=0 F1=0.000
76: EM=0 F1=0.098
77: EM=0 F1=0.000
78: EM=0 F1=0.000
79: EM=0 F1=0.258
80: EM=0 F1=0.000
81: EM=0 F1=0.000
82: EM=0 F1=0.067
83: EM=0 F1=0.000
84: EM=0 F1=0.077
85: EM=0 F1=0.000
86: EM=0 F1=0.000
87: EM=0 F1=0.000
88: EM=0 F1=0.000
89: EM=0 F1=0.129
90: EM=0 F1=0.000
91: EM=0 F1=0.190
92: EM=0 F1=0.000
93: EM=0 F1=0.200
94: EM=0 F1=0.167
95: EM=0 F1=0.000
96: EM=0 F1=0.000
97: EM=0 F1=0.000
98: EM=0 F1=0.333
99: EM=0 F1=0.067
100: EM=0 F1=0.087

In [55]:
!python scripts/evaluate_rollouts.py \
  --input /kaggle/working/artifacts/rl_rollouts.jsonl \
  --output /kaggle/working/artifacts/rl_metrics.json

{
  "examples": 100,
  "exact_match": 0.01,
  "token_f1": 0.0712646226441859,
  "reward": 0.035432311322092944,
  "valid_format_rate": 0.95,
  "search_rate": 0.25,
  "average_searches": 0.26
}

In [56]:
!cat /kaggle/working/artifacts/rl_metrics.json

{
  "examples": 100,
  "exact_match": 0.01,
  "token_f1": 0.0712646226441859,
  "reward": 0.035432311322092944,
  "valid_format_rate": 0.95,
  "search_rate": 0.25,
  "average_searches": 0.26
}

In [57]:
!cp -r \
  /kaggle/working/artifacts/qwen05b-search-rl \
  /kaggle/working/artifacts/qwen05b-search-rl-smoke-100-20

In [58]:
%cd /kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning
!git pull

/kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning
Already up to date.

In [59]:
!rm -rf /kaggle/working/artifacts/qwen05b-search-rl-500-50

In [60]:
!CUDA_VISIBLE_DEVICES=0 python scripts/train_rl.py \
  --train-data data/processed/train.jsonl \
  --passages data/processed/passages.jsonl \
  --output /kaggle/working/artifacts/qwen05b-search-rl-500-50 \
  --limit 500 \
  --max-steps 50

Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so
Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|███████████████████████| 290/290 [00:00<00:00, 566.05it/s]
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None}.
{'loss': '0.02573', 'grad_norm': '1.18', 'learning_rate': '1e-05', 'num_tokens': '1003', 'completions/mean_length': '123.5', 'completions/min_length': '119', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '119', 'completions/min_terminated_length': '119', 'completions/max_terminated_length': '119', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.6405', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '10.46', 'epoch': '0.002'}
{'loss': '-5.96e-08', 'grad_norm': '1.027', 'learning_rate': '9.8e-06', 'num_tokens': '2035', 'completions/mean_length': '128', 'completions/min_length': '128', 'completions/max_length': '128', 'completions/clipped_ratio': '1', 'completions/mean_terminated_length': '0', 'completions/min_terminated_length': '0', 'completions/max_terminated_length': '0', 'rewards/reward_function/mean': '-0.004746', 'rewards/reward_function/std': '0.001749', 'reward': '-0.004746', 'reward_std': '0.001749', 'frac_reward_zero_std': '0', 'entropy': '0.9412', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.302', 'epoch': '0.004'}
{'loss': '0', 'grad_norm': '0', 'learning_rate': '9.6e-06', 'num_tokens': '3258', 'completions/mean_length': '67.5', 'completions/min_length': '7', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '7', 'completions/min_terminated_length': '7', 'completions/max_terminated_length': '7', 'rewards/reward_function/mean': '-0.1', 'rewards/reward_function/std': '0', 'reward': '-0.1', 'reward_std': '0', 'frac_reward_zero_std': '1', 'entropy': '0.2805', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.361', 'epoch': '0.006'}
{'loss': '0', 'grad_norm': '1.153', 'learning_rate': '9.4e-06', 'num_tokens': '4242', 'completions/mean_length': '128', 'completions/min_length': '128', 'completions/max_length': '128', 'completions/clipped_ratio': '1', 'completions/mean_terminated_length': '0', 'completions/min_terminated_length': '0', 'completions/max_terminated_length': '0', 'rewards/reward_function/mean': '-0.0898', 'rewards/reward_function/std': '0.01443', 'reward': '-0.0898', 'reward_std': '0.01443', 'frac_reward_zero_std': '0', 'entropy': '1.165', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.365', 'epoch': '0.008'}
{'loss': '0.5405', 'grad_norm': '1.568', 'learning_rate': '9.2e-06', 'num_tokens': '5321', 'completions/mean_length': '72.5', 'completions/min_length': '17', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '17', 'completions/min_terminated_length': '17', 'completions/max_terminated_length': '17', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.7224', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.346', 'epoch': '0.01'}
{'loss': '3.248e-06', 'grad_norm': '0.9885', 'learning_rate': '9e-06', 'num_tokens': '6307', 'completions/mean_length': '128', 'completions/min_length': '128', 'completions/max_length': '128', 'completions/clipped_ratio': '1', 'completions/mean_terminated_length': '0', 'completions/min_terminated_length': '0', 'completions/max_terminated_length': '0', 'rewards/reward_function/mean': '-0.08074', 'rewards/reward_function/std': '0.001048', 'reward': '-0.08074', 'reward_std': '0.001048', 'frac_reward_zero_std': '0', 'entropy': '1.017', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.309', 'epoch': '0.012'}
{'loss': '0', 'grad_norm': '0', 'learning_rate': '8.8e-06', 'num_tokens': '7462', 'completions/mean_length': '107.5', 'completions/min_length': '87', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '87', 'completions/min_terminated_length': '87', 'completions/max_terminated_length': '87', 'rewards/reward_function/mean': '0', 'rewards/reward_function/std': '0', 'reward': '0', 'reward_std': '0', 'frac_reward_zero_std': '1', 'entropy': '0.7789', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.34', 'epoch': '0.014'}
{'loss': '0', 'grad_norm': '0.9454', 'learning_rate': '8.6e-06', 'num_tokens': '8612', 'completions/mean_length': '128', 'completions/min_length': '128', 'completions/max_length': '128', 'completions/clipped_ratio': '1', 'completions/mean_terminated_length': '0', 'completions/min_terminated_length': '0', 'completions/max_terminated_length': '0', 'rewards/reward_function/mean': '-0.08397', 'rewards/reward_function/std': '0.006786', 'reward': '-0.08397', 'reward_std': '0.006786', 'frac_reward_zero_std': '0', 'entropy': '0.718', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.346', 'epoch': '0.016'}
{'loss': '0.403', 'grad_norm': '1.533', 'learning_rate': '8.4e-06', 'num_tokens': '9697', 'completions/mean_length': '81.5', 'completions/min_length': '35', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '35', 'completions/min_terminated_length': '35', 'completions/max_terminated_length': '35', 'rewards/reward_function/mean': '-0.03157', 'rewards/reward_function/std': '0.08392', 'reward': '-0.03157', 'reward_std': '0.08392', 'frac_reward_zero_std': '0', 'entropy': '0.4442', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.361', 'epoch': '0.018'}
{'loss': '0.008373', 'grad_norm': '0.952', 'learning_rate': '8.2e-06', 'num_tokens': '1.089e+04', 'completions/mean_length': '126.5', 'completions/min_length': '125', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '125', 'completions/min_terminated_length': '125', 'completions/max_terminated_length': '125', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.7075', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.28', 'epoch': '0.02'}
{'loss': '0', 'grad_norm': '0', 'learning_rate': '8e-06', 'num_tokens': '1.16e+04', 'completions/mean_length': '41', 'completions/min_length': '10', 'completions/max_length': '72', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '41', 'completions/min_terminated_length': '10', 'completions/max_terminated_length': '72', 'rewards/reward_function/mean': '0', 'rewards/reward_function/std': '0', 'reward': '0', 'reward_std': '0', 'frac_reward_zero_std': '1', 'entropy': '0.7739', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '4.744', 'epoch': '0.022'}
{'loss': '-5.662e-07', 'grad_norm': '1.276', 'learning_rate': '7.8e-06', 'num_tokens': '1.287e+04', 'completions/mean_length': '128', 'completions/min_length': '128', 'completions/max_length': '128', 'completions/clipped_ratio': '1', 'completions/mean_terminated_length': '0', 'completions/min_terminated_length': '0', 'completions/max_terminated_length': '0', 'rewards/reward_function/mean': '-0.08632', 'rewards/reward_function/std': '0.006369', 'reward': '-0.08632', 'reward_std': '0.006369', 'frac_reward_zero_std': '0', 'entropy': '0.8733', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.473', 'epoch': '0.024'}
{'loss': '0', 'grad_norm': '0', 'learning_rate': '7.6e-06', 'num_tokens': '1.466e+04', 'completions/mean_length': '116', 'completions/min_length': '115', 'completions/max_length': '117', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '116', 'completions/min_terminated_length': '115', 'completions/max_terminated_length': '117', 'rewards/reward_function/mean': '0', 'rewards/reward_function/std': '0', 'reward': '0', 'reward_std': '0', 'frac_reward_zero_std': '1', 'entropy': '0.9117', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '7.929', 'epoch': '0.026'}
{'loss': '0.3828', 'grad_norm': '1.29', 'learning_rate': '7.4e-06', 'num_tokens': '1.569e+04', 'completions/mean_length': '83', 'completions/min_length': '38', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '38', 'completions/min_terminated_length': '38', 'completions/max_terminated_length': '38', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.4675', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.367', 'epoch': '0.028'}
{'loss': '0', 'grad_norm': '0.6628', 'learning_rate': '7.2e-06', 'num_tokens': '1.702e+04', 'completions/mean_length': '128', 'completions/min_length': '128', 'completions/max_length': '128', 'completions/clipped_ratio': '1', 'completions/mean_terminated_length': '0', 'completions/min_terminated_length': '0', 'completions/max_terminated_length': '0', 'rewards/reward_function/mean': '-0.05421', 'rewards/reward_function/std': '0.0201', 'reward': '-0.05421', 'reward_std': '0.0201', 'frac_reward_zero_std': '0', 'entropy': '0.04987', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.418', 'epoch': '0.03'}
{'loss': '0', 'grad_norm': '0', 'learning_rate': '7e-06', 'num_tokens': '1.785e+04', 'completions/mean_length': '91.5', 'completions/min_length': '55', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '55', 'completions/min_terminated_length': '55', 'completions/max_terminated_length': '55', 'rewards/reward_function/mean': '-0.1', 'rewards/reward_function/std': '0', 'reward': '-0.1', 'reward_std': '0', 'frac_reward_zero_std': '1', 'entropy': '0.4425', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.322', 'epoch': '0.032'}
{'loss': '-0.05639', 'grad_norm': '1.439', 'learning_rate': '6.8e-06', 'num_tokens': '1.883e+04', 'completions/mean_length': '118.5', 'completions/min_length': '109', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '109', 'completions/min_terminated_length': '109', 'completions/max_terminated_length': '109', 'rewards/reward_function/mean': '-0.08649', 'rewards/reward_function/std': '0.01911', 'reward': '-0.08649', 'reward_std': '0.01911', 'frac_reward_zero_std': '0', 'entropy': '1.003', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.214', 'epoch': '0.034'}
{'loss': '0.4601', 'grad_norm': '1.67', 'learning_rate': '6.6e-06', 'num_tokens': '1.986e+04', 'completions/mean_length': '77.5', 'completions/min_length': '27', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '27', 'completions/min_terminated_length': '27', 'completions/max_terminated_length': '27', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.8368', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.254', 'epoch': '0.036'}
{'loss': '0.2055', 'grad_norm': '2.201', 'learning_rate': '6.4e-06', 'num_tokens': '2.076e+04', 'completions/mean_length': '99', 'completions/min_length': '70', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '70', 'completions/min_terminated_length': '70', 'completions/max_terminated_length': '70', 'rewards/reward_function/mean': '-0.06975', 'rewards/reward_function/std': '0.01268', 'reward': '-0.06975', 'reward_std': '0.01268', 'frac_reward_zero_std': '0', 'entropy': '0.9536', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.248', 'epoch': '0.038'}
{'loss': '0', 'grad_norm': '1.124', 'learning_rate': '6.2e-06', 'num_tokens': '2.163e+04', 'completions/mean_length': '128', 'completions/min_length': '128', 'completions/max_length': '128', 'completions/clipped_ratio': '1', 'completions/mean_terminated_length': '0', 'completions/min_terminated_length': '0', 'completions/max_terminated_length': '0', 'rewards/reward_function/mean': '-0.08889', 'rewards/reward_function/std': '0.01571', 'reward': '-0.08889', 'reward_std': '0.01571', 'frac_reward_zero_std': '0', 'entropy': '1.031', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.244', 'epoch': '0.04'}
{'loss': '-0.02926', 'grad_norm': '1.551', 'learning_rate': '6e-06', 'num_tokens': '2.25e+04', 'completions/mean_length': '90.5', 'completions/min_length': '86', 'completions/max_length': '95', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '90.5', 'completions/min_terminated_length': '86', 'completions/max_terminated_length': '95', 'rewards/reward_function/mean': '0.06487', 'rewards/reward_function/std': '0.0004959', 'reward': '0.06487', 'reward_std': '0.0004959', 'frac_reward_zero_std': '0', 'entropy': '0.7072', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '6.149', 'epoch': '0.042'}
{'loss': '0', 'grad_norm': '0', 'learning_rate': '5.8e-06', 'num_tokens': '2.35e+04', 'completions/mean_length': '10', 'completions/min_length': '10', 'completions/max_length': '10', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '10', 'completions/min_terminated_length': '10', 'completions/max_terminated_length': '10', 'rewards/reward_function/mean': '0', 'rewards/reward_function/std': '0', 'reward': '0', 'reward_std': '0', 'frac_reward_zero_std': '1', 'entropy': '0.2036', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '1.093', 'epoch': '0.044'}
{'loss': '0.1324', 'grad_norm': 'nan', 'learning_rate': '5.6e-06', 'num_tokens': '2.413e+04', 'completions/mean_length': '16', 'completions/min_length': '13', 'completions/max_length': '19', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '16', 'completions/min_terminated_length': '13', 'completions/max_terminated_length': '19', 'rewards/reward_function/mean': '-0.05', 'rewards/reward_function/std': '0.07071', 'reward': '-0.05', 'reward_std': '0.07071', 'frac_reward_zero_std': '0', 'entropy': '0.6241', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '1.517', 'epoch': '0.046'}
{'loss': '0.2873', 'grad_norm': '1.527', 'learning_rate': '5.4e-06', 'num_tokens': '2.504e+04', 'completions/mean_length': '91', 'completions/min_length': '54', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '54', 'completions/min_terminated_length': '54', 'completions/max_terminated_length': '54', 'rewards/reward_function/mean': '0.02617', 'rewards/reward_function/std': '0.1201', 'reward': '0.02617', 'reward_std': '0.1201', 'frac_reward_zero_std': '0', 'entropy': '1.511', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.315', 'epoch': '0.048'}
{'loss': '0.6238', 'grad_norm': '4.578', 'learning_rate': '5.2e-06', 'num_tokens': '2.608e+04', 'completions/mean_length': '68', 'completions/min_length': '8', 'completions/max_length': '128', 'completions/clipped_ratio': '0.5', 'completions/mean_terminated_length': '8', 'completions/min_terminated_length': '8', 'completions/max_terminated_length': '8', 'rewards/reward_function/mean': '0.4557', 'rewards/reward_function/std': '0.7697', 'reward': '0.4557', 'reward_std': '0.7697', 'frac_reward_zero_std': '0', 'entropy': '0.5984', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '8.311', 'epoch': '0.05'}
{'loss': '0', 'grad_norm': '0', 'learning_rate': '5e-06', 'num_tokens': '2.689e+04', 'completions/mean_length': '11', 'completions/min_length': '11', 'completions/max_length': '11', 'completions/clipped_ratio': '0', 'completions/mean_terminated_length': '11', 'completions/min_terminated_length': '11', 'completions/max_terminated_length': '11', 'rewards/reward_function/mean': '0', 'rewards/reward_function/std': '0', 'reward': '0', 'reward_std': '0', 'frac_reward_zero_std': '1', 'entropy': '0.4243', 'clip_ratio/low_mean': '0', 'clip_ratio/high_mean': '0', 'clip_ratio/region_mean': '0', 'clip_ratio/low_min': '0', 'clip_ratio/high_max': '0', 'step_time': '1.137', 'epoch': '0.052'}

In [61]:
!CUDA_VISIBLE_DEVICES=0 python scripts/run_qwen_baseline.py \
  --questions data/processed/validation.jsonl \
  --passages data/processed/passages.jsonl \
  --adapter /kaggle/working/artifacts/qwen05b-search-rl-500-50 \
  --output /kaggle/working/artifacts/rl_500_50_rollouts.jsonl \
  --limit 100

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so
Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so
Loading weights: 100%|███████████████████████| 290/290 [00:00<00:00, 874.13it/s]
1: EM=0 F1=0.000
2: EM=0 F1=0.000
3: EM=1 F1=1.000
4: EM=0 F1=0.000
5: EM=0 F1=0.000
6: EM=0 F1=0.000
7: EM=0 F1=0.308
8: EM=0 F1=0.000
9: EM=0 F1=0.000
10: EM=0 F1=0.000
11: EM=0 F1=0.067
12: EM=0 F1=0.341
13: EM=0 F1=0.000
14: EM=0 F1=0.000
15: EM=0 F1=0.100
16: EM=0 F1=0.000
17: EM=0 F1=0.000
18: EM=0 F1=0.000
19: EM=0 F1=0.009
20: EM=0 F1=0.400
21: EM=0 F1=0.000
22: EM=0 F1=0.000
23: EM=0 F1=0.057
24: EM=0 F1=0.078
25: EM=0 F1=0.000
26: EM=0 F1=0.800
27: EM=0 F1=0.000
28: EM=0 F1=0.000
29: EM=0 F1=0.000
30: EM=0 F1=0.013
31: EM=0 F1=0.000
32: EM=0 F1=0.000
33: EM=0 F1=0.143
34: EM=0 F1=0.004
35: EM=0 F1=0.000
36: EM=0 F1=0.400
37: EM=0 F1=0.000
38: EM=0 F1=0.600
39: EM=0 F1=0.000
40: EM=0 F1=0.222
41: EM=0 F1=0.000
42: EM=0 F1=0.000
43: EM=0 F1=0.000
44: EM=0 F1=0.000
45: EM=0 F1=0.000
46: EM=0 F1=0.035
47: EM=0 F1=0.000
48: EM=0 F1=0.000
49: EM=0 F1=0.000
50: EM=0 F1=0.000
51: EM=0 F1=0.000
52: EM=0 F1=0.000
53: EM=0 F1=0.018
54: EM=0 F1=0.000
55: EM=0 F1=0.214
56: EM=0 F1=0.000
57: EM=0 F1=0.000
58: EM=0 F1=0.211
59: EM=0 F1=0.111
60: EM=0 F1=0.000
61: EM=0 F1=0.091
62: EM=0 F1=0.000
63: EM=0 F1=0.000
64: EM=0 F1=0.000
65: EM=0 F1=0.000
66: EM=0 F1=0.000
67: EM=0 F1=0.000
68: EM=0 F1=0.000
69: EM=1 F1=1.000
70: EM=0 F1=0.036
71: EM=0 F1=0.154
72: EM=0 F1=0.000
73: EM=0 F1=0.118
74: EM=0 F1=0.500
75: EM=0 F1=0.000
76: EM=0 F1=0.098
77: EM=0 F1=0.000
78: EM=0 F1=0.000
79: EM=0 F1=0.258
80: EM=0 F1=0.108
81: EM=0 F1=0.000
82: EM=0 F1=0.067
83: EM=0 F1=0.000
84: EM=0 F1=0.038
85: EM=0 F1=0.000
86: EM=0 F1=0.000
87: EM=0 F1=0.000
88: EM=0 F1=0.000
89: EM=0 F1=0.129
90: EM=0 F1=0.000
91: EM=0 F1=0.308
92: EM=0 F1=0.000
93: EM=0 F1=0.200
94: EM=0 F1=0.167
95: EM=0 F1=0.000
96: EM=0 F1=0.000
97: EM=0 F1=0.000
98: EM=0 F1=0.333
99: EM=0 F1=0.061
100: EM=0 F1=0.160

In [62]:
!python scripts/evaluate_rollouts.py \
  --input /kaggle/working/artifacts/rl_500_50_rollouts.jsonl \
  --output /kaggle/working/artifacts/rl_500_50_metrics.json

{
  "examples": 100,
  "exact_match": 0.02,
  "token_f1": 0.08956426955727043,
  "reward": 0.045782134778635214,
  "valid_format_rate": 0.92,
  "search_rate": 0.29,
  "average_searches": 0.34
}

In [63]:
!cat /kaggle/working/artifacts/rl_500_50_metrics.json

{
  "examples": 100,
  "exact_match": 0.02,
  "token_f1": 0.08956426955727043,
  "reward": 0.045782134778635214,
  "valid_format_rate": 0.92,
  "search_rate": 0.29,
  "average_searches": 0.34
}