In [1]:
!git clone https://github.com/Shubham-joshi20/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning.git

Cloning into 'Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 40 (delta 10), reused 36 (delta 9), pack-reused 0 (from 0)
Receiving objects: 100% (40/40), 20.53 KiB | 3.42 MiB/s, done.
Resolving deltas: 100% (10/10), done.

In [2]:
%cd /kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning

/kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning

In [3]:
!git pull origin main

From https://github.com/Shubham-joshi20/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning
 * branch            main       -> FETCH_HEAD
Already up to date.

In [4]:
pip install -q -r requirements.txt

Note: you may need to restart the kernel to use updated packages.

In [5]:
from pathlib import Path

for path in Path("/kaggle/input").rglob("*"):
    if path.is_file():
        print(path)

/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv
/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv

In [6]:
!python scripts/prepare_nq.py \
  --input /kaggle/input/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv//kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv \
  --output data/processed/train.jsonl \
  --split train \
  --limit 5000

Traceback (most recent call last):
  File "/kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning/scripts/prepare_nq.py", line 32, in <module>
    main()
    ~~~~^^
  File "/kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning/scripts/prepare_nq.py", line 27, in main
    summary = prepare_subset(args.input, args.output, args.split, args.limit, args.seed)
  File "/kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning/src/search_rl/data.py", line 127, in prepare_subset
    records = read_records(input_path)
  File "/kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning/src/search_rl/data.py", line 109, in read_records
    with path.open(newline="", encoding="utf-8-sig") as handle:
         ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/pathlib/_local.py", line 537, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv'

In [7]:
!git clone https://github.com/Shubham-joshi20/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning.git

Cloning into 'Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 40 (delta 10), reused 36 (delta 9), pack-reused 0 (from 0)
Receiving objects: 100% (40/40), 20.53 KiB | 10.26 MiB/s, done.
Resolving deltas: 100% (10/10), done.

In [8]:
cd Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning

/kaggle/working/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning

In [9]:
!python scripts/prepare_nq.py

usage: prepare_nq.py [-h] --input INPUT --output OUTPUT [--split SPLIT]
                     [--limit LIMIT] [--seed SEED]
prepare_nq.py: error: the following arguments are required: --input, --output

In [10]:
!git pull origin main

From https://github.com/Shubham-joshi20/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning
 * branch            main       -> FETCH_HEAD
Already up to date.

In [11]:
from pathlib import Path

for path in Path("/kaggle/input/datasets/frankossai/natural-questions-dataset").rglob("*"):
    if path.is_file():
        print(path)

/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv
/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv

In [12]:
import pandas as pd

base_path = "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv"
filtered_path = "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv"

for path in [base_path, filtered_path]:
    df = pd.read_csv(path)
    print("\nFILE:", path)
    print("Shape:", df.shape)
    print("Columns:", list(df.columns))
    display(df.head(2))

FILE: /kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv
Shape: (307373, 3)
Columns: ['question', 'long_answers', 'short_answers']

,question,long_answers,short_answers
0,which is the most common use of opt-in e-mail ...,<P> A common example of permission marketing i...,a newsletter sent to an advertising firm 's cu...
1,how i.met your mother who is the mother,"<P> Tracy McConnell , better known as `` The M...",Tracy McConnell

FILE: /kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv
Shape: (86212, 3)
Columns: ['question', 'long_answers', 'short_answers']

,question,long_answers,short_answers
0,which is the most common use of opt-in e-mail ...,A common example of permission marketing is a ...,A newsletter sent to an advertising firm's cus...
1,how i.met your mother who is the mother,"Tracy McConnell, better known as `` The Mother...",Tracy McConnell

In [13]:
%run scripts/prepare_nq.py --input "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv" --output "/kaggle/working/data/processed/train.jsonl" --split train --limit 5000 --seed 42

{
  "input_records": 86212,
  "usable_records": 86212,
  "written_records": 5000
}

In [14]:
!pip install -q -r requirements.txt

In [15]:
import pandas as pd

path = "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv"

df = pd.read_csv(path)
print(df.columns.tolist())
display(df.head(2))

['question', 'long_answers', 'short_answers']

,question,long_answers,short_answers
0,which is the most common use of opt-in e-mail ...,A common example of permission marketing is a ...,A newsletter sent to an advertising firm's cus...
1,how i.met your mother who is the mother,"Tracy McConnell, better known as `` The Mother...",Tracy McConnell

In [16]:
%run scripts/prepare_passages.py --input "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv" --output "/kaggle/working/data/processed/passages.jsonl" --max-records 5000

Wrote 6453 passages to /kaggle/working/data/processed/passages.jsonl

In [17]:
import pandas as pd

base_path = "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv"
filtered_path = "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv"

for path in [filtered_path, base_path]:
    df = pd.read_csv(path)
    print("\nFILE:", path)
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())
    display(df.head(1).T)

FILE: /kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv
Shape: (86212, 3)
Columns: ['question', 'long_answers', 'short_answers']

                                                               0
question       which is the most common use of opt-in e-mail ...
long_answers   A common example of permission marketing is a ...
short_answers  A newsletter sent to an advertising firm's cus...

FILE: /kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Base.csv
Shape: (307373, 3)
Columns: ['question', 'long_answers', 'short_answers']

                                                               0
question       which is the most common use of opt-in e-mail ...
long_answers   <P> A common example of permission marketing i...
short_answers  a newsletter sent to an advertising firm 's cu...

In [18]:
df = pd.read_csv(base_path)

possible_columns = [
    "document_text",
    "context",
    "passage",
    "long_answer",
    "document",
    "text"
]

for column in possible_columns:
    if column in df.columns:
        print(column, "non-empty values:", df[column].notna().sum())
        print(df[column].dropna().iloc[0][:500])

In [19]:
!git pull origin main

From https://github.com/Shubham-joshi20/Training-Large-Language-Models-to-Reason-and-Leverage-Search-Engines-with-Reinforcement-Learning
 * branch            main       -> FETCH_HEAD
Already up to date.

In [20]:
%run scripts/prepare_passages.py \
  --input "/kaggle/input/datasets/frankossai/natural-questions-dataset/Natural-Questions-Filtered.csv" \
  --output "/kaggle/working/data/processed/passages.jsonl" \
  --max-records 5000 \
  --words-per-passage 120

Wrote 6453 passages to /kaggle/working/data/processed/passages.jsonl

In [21]:
from pathlib import Path

path = Path("/kaggle/working/data/processed/passages.jsonl")

print("Passage file exists:", path.exists())
print("Number of passages:", len(path.read_text(encoding="utf-8").splitlines()))
print(path.read_text(encoding="utf-8").splitlines()[:2])

Passage file exists: True
Number of passages: 6453
['{"id": "nq-0-0", "text": "A common example of permission marketing is a newsletter sent to an advertising firm\'s customers. Such newsletters inform customers of upcoming events or promotions, or new products. In this type of advertising, a company that wants to send a newsletter to their customers may ask them at the point of purchase if they would like to receive the newsletter."}', '{"id": "nq-1-0", "text": "Tracy McConnell, better known as `` The Mother \'\', is the title character from the CBS television sitcom How I Met Your Mother. The show, narrated by Future Ted, tells the story of how Ted Cosby met The Mother. Tracy McConnell appears in episodes from `` Lucky Penny \'\' to `` The Time Travelers \'\' as an unseen character ; she was first seen fully in `` Something New \'\' and was promoted to a main character in season. The Mother is played by Cristina Militia."}']